### ISSUE TITLE
TP terminé

### ISSUE THREAD

**Issue by AliciaRocchia** [PolytechLyon/2019-isi3-graph-rocchia_marsangy#1]
Bonsoir, notre TP est terminé.
Bonne soirée

**Comment by Slashgear** [comment]
- 👍 Rapport
- Rien à redire sur adapter
- rien à redire sur Itérateur

Dans l'ensemble c'est très bien! 

Si vous voulez apprendre et expérimenter la programmation fonctionnelle qui pourrait vous simplifier l'écriture de votre toString

https://github.com/PolytechLyon/2019-isi3-graph-rocchia_marsangy/blob/4d95c16716dbc99ac344c4a6f3d149e868cab6bc/src/main/java/graph/Graph.java#L78-L100
